# Generated by Django 5.0.2 on 2024-04-15 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0003_alter_like_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="follow",
            name="follower",
        ),
        migrations.RemoveField(
            model_name="follow",
            name="following",
        ),
        migrations.AddField(
            model_name="follow",
            name="user_followed",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers_list",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="follow",
            name="user_following",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following_list",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
