# Generated by Django 5.0.2 on 2024-04-17 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0004_remove_follow_follower_remove_follow_following_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("user_following", "user_followed")},
        ),
    ]
