# Generated by Django 5.0.2 on 2024-04-17 12:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0005_alter_follow_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("user", "post")},
        ),
        migrations.RemoveField(
            model_name="like",
            name="like",
        ),
    ]
